
softwareconfig:
  appkgschedule: 0 0 1 * * ?
  appkgOsSchedule: 0 0 3 * * ?
  rpmSchedule: 0 0 3 * * ?



softcenter:

  rpm:
    repoInfo:
   
      sourcePath:
    forkInfo:
      
      accessToken: 
      owner: 
      email: 
      name: 
      password: 
      scope: 
      clientId: 
      clientSecret: 






server:
  port: 8080

